DROP TABLE IF EXISTS "public"."sc_tag";
CREATE TABLE "public"."sc_tag" (
  "id" SERIAL PRIMARY KEY,
  "name" VARCHAR(255) UNIQUE NOT NULL,
  "num" INTEGER NOT NULL,
  "create_time" TIMESTAMP NOT NULL DEFAULT TIMEZONE('UTC-8'::TEXT, NOW()::TIMESTAMP(0) WITHOUT TIME ZONE)
)
;